--INSERT INTO STUDENT VALUES(hibernate_sequence.NEXTVAL,'Ali','Aliyev');
--INSERT INTO STUDENT VALUES(hibernate_sequence.NEXTVAL,'Gunel','Huseynova');
--INSERT INTO STUDENT VALUES(hibernate_sequence.NEXTVAL,'Yashar','Nuriyev');
--INSERT INTO COURSE VALUES(1,'INFT-1101','Web & Mobile I');
--INSERT INTO COURSE VALUES(2,'INFT-1102','Web & Mobile II');
--INSERT INTO COURSE VALUES(3,'INFT-1103','IT Project Management');
--INSERT INTO COURSE VALUES(4,'INFT-1104','System Analysis and Design');
--INSERT INTO STUDENT_ENROLLED_COURSES VALUES(1,1);
--INSERT INTO STUDENT_ENROLLED_COURSES VALUES(1,2);
--INSERT INTO STUDENT_ENROLLED_COURSES VALUES(2,1);

INSERT INTO PASSENGER VALUES(1,'Name','Lastname','1346543212');
INSERT INTO PASSENGER VALUES(2,'Name 2','Lastname 2','1310953211');
INSERT INTO PASSENGER VALUES(3,'Name 3','Lastname 3','1566543212');

INSERT INTO TRIP VALUES(1, 'Driver 1', 'Surname 1', '533440585', 'Reno');
INSERT INTO TRIP VALUES(2, 'Driver 2', 'Surname 2', '533444321', 'Fiat');