--INSERT INTO STUDENT VALUES(hibernate_sequence.NEXTVAL,'Ali','Aliyev');
--INSERT INTO STUDENT VALUES(hibernate_sequence.NEXTVAL,'Gunel','Huseynova');
--INSERT INTO STUDENT VALUES(hibernate_sequence.NEXTVAL,'Yashar','Nuriyev');
--INSERT INTO COURSE VALUES(1,'INFT-1101','Web & Mobile I');
--INSERT INTO COURSE VALUES(2,'INFT-1102','Web & Mobile II');
--INSERT INTO COURSE VALUES(3,'INFT-1103','IT Project Management');
--INSERT INTO COURSE VALUES(4,'INFT-1104','System Analysis and Design');
--INSERT INTO STUDENT_ENROLLED_COURSES VALUES(1,1);
--INSERT INTO STUDENT_ENROLLED_COURSES VALUES(1,2);
--INSERT INTO STUDENT_ENROLLED_COURSES VALUES(2,1);

INSERT INTO PASSENGER VALUES(1,"Name","Lasname","1345435345");
--INSERT INTO TRIP VALUES(1,2);
--INSERT INTO MESSAGE VALUES(2,1);
